#! /bin/sh

# Edit these!
WLAN_DEVICE=wlp3s0
WPA_CONF=/etc/wpa_supplicant.conf

# Use sudo if it exists. Edit this if you use another privesc program than sudo.
SUDO="$(which sudo || printf "")"

# You don't need to edit these
WPA_PID_FILE=/run/wpa_supplicant/pid
IS_ACTIVE_FILE=/run/wctl/stat


case "$1" in
	e|enable)
		[ -f "$IS_ACTIVE_FILE" ] || {
			"$SUDO" mkdir -p "${WPA_PID_FILE%/*}"
			"$SUDO" mkdir -p "${IS_ACTIVE_FILE%/*}"
			"$SUDO" touch "$WPA_PID_FILE" || exit
			"$SUDO" wpa_supplicant -B -i "$WLAN_DEVICE" -c "$WPA_CONF" -P "$WPA_PID_FILE"
			"$SUDO" dhcpcd
		}
		;;
	d|disable)
		[ -f "$IS_ACTIVE_FILE" ] && {
			"$SUDO" rm -rf "${WPA_PID_FILE%/*}"
			"$SUDO" rm -rf "${IS_ACTIVE_FILE%/*}"
			"$SUDO" touch "$WPA_PID_FILE" || exit
			"$SUDO" kill "$(cat "$WPA_PID_FILE")"
			"$SUDO" rm -f "$IS_ACTIVE_FILE"
			"$SUDO" dhcpcd -k
		}
		;;
	r|restart)
		[ -f "$IS_ACTIVE_FILE" ] || {
			"$0" d
			"$0" e
		}
		;;
	s|status)
		ip addr | sed "1,/"$WLAN_DEVICE"/ d"
		;;
	*)
		echo "Usage: wctl [ enable / disable / restart / status ]"
		;;
esac
