#!/bin/sh
[ -z "$1" ] && exit 1
find_file () {
    for file in "$2"/*; do
        [ -f "$file" ] &&
            case "$file" in
                *"$1"*) printf '%s\n' "$file";;
            esac
        [ -d "$file" ] && find_file "$1" "$file"
    done
}
IFS=:
for path in $MANPATH; do
    [ -e "$path" ] || continue
    find_file "$1" "$path"
done
