#! /bin/sh

which doas > /dev/null && SUDO=doas
which sudo > /dev/null && SUDO=sudo

[ -z "$2" ] && set -- "$1" "1"

BRIF="PATH_PLACEHOLDER"

case "$1" in
	i|inc)
		echo $(( $(cat "$BRIF") + "$2" )) | "$SUDO" tee "$BRIF" > /dev/null
		;;
	d|dec)
		echo $(( $(cat "$BRIF") - "$2" )) | "$SUDO" tee "$BRIF" > /dev/null
		;;
	s|set)
		echo "$2" | "$SUDO" tee "$BRIF" > /dev/null
		;;
	g|get)
		cat "$BRIF"
		;;
esac
