#! /bin/sh

which doas > /dev/null && SUDO=doas
which sudo > /dev/null && SUDO=sudo

[ -z "$2" ] && set -- "$1" "1"

BRIF="PATH_PLACEHOLDER"

case "$1" in
	i|inc)
		echo $(( $(cat "$BRIF") + $2 )) | "$SUDO" tee "$BRIF" > /dev/null
		;;
	d|dec)
		echo $(( $(cat "$BRIF") - $2 )) | "$SUDO" tee "$BRIF" > /dev/null
		;;
	m|max)
		if [ -f "${BRIF%/*}/max_brightness" ]; then
			"$SUDO" tee "$BRIF" < "${BRIF%/*}/max_brightness" > /dev/null
		else
			echo 100 | "$SUDO" tee "$BRIF" > /dev/null
		fi
		;;
	s|set)
		echo "$2" | "$SUDO" tee "$BRIF" > /dev/null
		;;
	g|get)
		cat "$BRIF"
		;;
esac
