#! /bin/sh

WLAN_DEVICE="DEV_PLACEHOLDER"
WPA_CONF="WPA_PLACEHOLDER"

which doas > /dev/null && SUDO=doas
which sudo > /dev/null && SUDO=sudo

WPA_PID_FILE=/run/wpa_supplicant/pid
IS_ACTIVE_FILE=/run/wctl/stat

case "$1" in
	e|enable)
		[ -f "$IS_ACTIVE_FILE" ] || {
			"$SUDO" mkdir -p "${WPA_PID_FILE%/*}"
			"$SUDO" mkdir -p "${IS_ACTIVE_FILE%/*}"
			"$SUDO" touch "$WPA_PID_FILE" || exit
			"$SUDO" wpa_supplicant -B -i "$WLAN_DEVICE" -c "$WPA_CONF" -P "$WPA_PID_FILE"
			"$SUDO" dhcpcd
		}
		;;
	d|disable)
		[ -f "$IS_ACTIVE_FILE" ] && {
			"$SUDO" rm -rf "${WPA_PID_FILE%/*}"
			"$SUDO" rm -rf "${IS_ACTIVE_FILE%/*}"
			"$SUDO" touch "$WPA_PID_FILE" || exit
			"$SUDO" kill "$(cat "$WPA_PID_FILE")"
			"$SUDO" rm -f "$IS_ACTIVE_FILE"
			"$SUDO" dhcpcd -k
		}
		;;
	s|status)
		ip addr | sed "1,/"$WLAN_DEVICE"/ d"
		;;
	l|list)
		grep '^\s*ssid="[a-zA-Z0-9]*"\s*$' "$WPA_CONF" | cut -d'"' -f2
		;;
	a|add)
		[ -z "$2" ] && {
			echo 'Usage: wctl [ enable / disable / restart / status / list / add <ssid> [psk] / remove <ssid> ]'
			exit
		}
		printf 'network={\n\tssid="%s"\n\tpsk="%s"\n}\n' "$2" "$3" \
			| "$SUDO" tee -a "$WPA_CONF" > /dev/null
		;;
	r|remove)
		[ -z "$2" ] && {
			echo 'Usage: wctl [ enable / disable / restart / status / list / add <ssid> [psk] / remove <ssid> ]'
			exit
		}
		grep -q "^\s*ssid=\"$2\"\s*$" "$WPA_CONF" || {
			echo "No net with ssid '$2' could be found."
			exit
		}
		SSIDR="$(sed -n "/^\s*ssid=\"$2\"\s*$/=" "$WPA_CONF")"
		sed "$(expr "$SSIDR" - 1),$(expr "$SSIDR" + 2)d" "$WPA_CONF" \
			| "$SUDO" tee "$WPA_CONF" > /dev/null
		;;
	*)
		echo 'Usage: wctl [ enable / disable / status / list / add <ssid> [psk] / remove <ssid> ]'
		;;
esac
